theme: jekyll-theme-hacker
# Jose's First CS 193

My favorite things about CS193:
- The TAs are really cool and understand us better. 
- They post W memes on the presentations.
- TAs talk like us and are young.
